name: CreeperHeal
main: com.nitnelave.CreeperHeal.CreeperHeal
version: 6.0
author: nitnelave
description: Replaces terrain destroyed by creeper explosions
softdepend: [LWC, Lockette, MobArena, Factions, bPermissions, PlayerHeads]

commands:
    CreeperHeal:
        description: CreeperHeal commands
        usage: /<command> help
        alias: ch

permissions:
    CreeperHeal.*:
        description: Gives access to all CreeperHeal commands
        children:
            CreeperHeal.admin: true
            CreeperHeal.heal: true
    CreeperHeal.admin:
        description: Config and heal commands
        default: op
    CreeperHeal.heal:
        description: Heal explosions (heal and healBurnt commands)
        default: op
    CreeperHeal.healNear.self:
        description: Heal explosions nearby (/ch healNear)
        default: op
    CreeperHeal.healNear.other:
        description: Heal explosions nearby a given player (/ch healNear player)
        default: op
